### ISSUE TITLE
Check units of the source RAS model 

### ISSUE THREAD

**Issue by mdeshotel** [Dewberry/ripple1d#72] opened 2024-07-18 20:16 UTC
There is a slight chance not all source models will be in feet. We should try to infer from the source RAS model what units were used and then handle this as necessary during Terrain build, ripple processing, metadata, etc.

**Comment by ar-siddiqui** [comment] 2024-08-21 21:01
duplicate of #123

**Closed by ar-siddiqui** 2024-08-21 21:01 UTC
